//-----------------------------------------------------------------------------
// Brainfuck BASIC compiler
// Copyright (c) Paulo Custodio 2026
// License: The Artistic License 2.0, http ://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "codegen.h"
#include <algorithm>
#include <cassert>

CodeGen::CodeGen(SymbolTable& sym)
    : sym(sym), temp_counter(0) {
}

std::string CodeGen::generate(const Program& prog) {
    out.clear();

    emit_prelude();
    emit_var_allocs();

    for (const auto& s : prog.statements) {
        emit_stmt(*s);
    }

    emit_postlude();
    return out;
}

void CodeGen::emit(const std::string& line) {
    out += line;
    out += "\n";
}

std::string CodeGen::alloc_temp16() {
    std::string name = "_BFB" + std::to_string(++temp_counter);
    emit("alloc_cell16(" + name + ")");
    return name;
}

std::string CodeGen::alloc_temp_string(int size) {
    std::string name = "_BFB" + std::to_string(++temp_counter) + "$";
    emit("alloc_array8(" + name + ", " + std::to_string(size + 1) + ")");
    return name;
}

void CodeGen::free_temp16(const std::string& name) {
    emit("free_cell16(" + name + ")");
}

void CodeGen::free_temp_string(const std::string& name) {
    emit("free_array8(" + name + ")");
}

std::vector<std::string> CodeGen::sorted_variable_names() const {
    std::vector<std::string> names;
    for (auto& [name, sym] : sym.all()) {
        names.push_back(name);
    }

    std::sort(names.begin(), names.end());
    return names;
}

void CodeGen::emit_prelude() {
    emit("// Generated by bfbasic, see https://github.com/pauloscustodio/bf");
}

void CodeGen::emit_postlude() {
    // optional: free vars, runtime cleanup
    // for now, do nothing
}

void CodeGen::emit_var_allocs() {
    auto names = sorted_variable_names();
    for (const auto& name : names) {
        const Symbol* symbol = sym.get(name);
        assert(symbol); // should exist

        switch (symbol->type) {
        case SymbolType::IntVar:
            emit("alloc_cell16(" + name + ")");
            break;
        case SymbolType::StringVar:
            emit("alloc_array8(" + name + ", " +
                 std::to_string(symbol->array_size + 1) + ")");
            break;
        case SymbolType::IntArrayVar:
            emit("alloc_array16(" + name + ", " +
                 std::to_string(symbol->array_size + 1) + ")");
            break;
        default:
            assert(0);
        }

        sym.mark_allocated(name);
    }
}

void CodeGen::emit_stmt(const Stmt& s) {
    switch (s.type) {
    case StmtType::Let:
        emit_let(s);
        break;
    case StmtType::Dim:
        emit_dim(s);
        break;
    case StmtType::Input:
        emit_input(s);
        break;
    case StmtType::Print:
        emit_print(s);
        break;
    case StmtType::If:
        emit_if(s);
        break;
    case StmtType::While:
        emit_while(s);
        break;
    case StmtType::For:
        emit_for(s);
        break;
    default:
        assert(0);
    }
}

void CodeGen::emit_input(const Stmt& s) {
    for (auto& v : s.input_stmt->vars) {
        emit("scan_cell16s(" + v + ")");
    }
}

void CodeGen::emit_print(const Stmt& s) {
    const PrintStmt& p = *s.print_stmt;
    bool last_was_separator = false;

    for (const auto& e : p.elems) {
        switch (e.type) {

        case PrintElemType::String:
            emit("print_string(\"" + escape(e.text) + "\")");
            last_was_separator = false;
            break;

        case PrintElemType::Expr: {
            switch (e.expr.value_type) {
            case ValueType::Int:
                if (e.expr.expr_type == ExprType::Var) {
                    emit("print_cell16s(" + e.expr.name + ")");
                }
                else {
                    std::string tmp = alloc_temp16();
                    emit_expr(e.expr, tmp);
                    emit("print_cell16s(" + tmp + ")");
                    free_temp16(tmp);
                }
                break;
            case ValueType::String:
                if (e.expr.expr_type == ExprType::Var) {
                    emit("print_string(" + e.expr.name + ")");
                }
                else {
                    std::string tmp = alloc_temp_string(e.expr.string_size);
                    emit_expr(e.expr, tmp);
                    emit("print_string(" + tmp + ")");
                    free_temp_string(tmp);
                }
                break;
            default:
                assert(0);
            }

            last_was_separator = false;
            break;
        }

        case PrintElemType::Separator:
            if (e.sep == TokenType::Comma) {
                emit("print_char(9)");    // tab
            }
            // semicolon prints nothing
            last_was_separator = true;
            break;
        }
    }

    // newline unless last element was a semicolon
    if (!last_was_separator) {
        emit("print_newline");
    }
}


std::string CodeGen::escape(const std::string& s) {
    std::string result;
    result.reserve(s.size());
    for (auto c : s) {
        if (c == '"') {
            result += "\\\"";
        }
        else {
            result.push_back(c);
        }
    }

    return result;
}

void CodeGen::emit_let(const Stmt& s) {
    std::string var = s.let_stmt->var;

    switch (s.let_stmt->type) {
    case LetType::Normal: {
        // Case 1: LET A = <constant>
        if (s.let_stmt->expr.expr_type == ExprType::Number) {
            emit("set16(" + var + ", " +
                 std::to_string(s.let_stmt->expr.int_value) + ")");
            return;
        }

        // Case 2: LET A = B
        if (s.let_stmt->expr.expr_type == ExprType::Var) {
            emit("copy16(" + s.let_stmt->expr.name + ", " + var + ")");
            return;
        }

        // General case: LET A = <complex expression>
        std::string t = alloc_temp16();
        emit_expr(s.let_stmt->expr, t);
        emit("move16(" + t + ", " + var + ")");
        free_temp16(t);
        break;
    }
    case LetType::Array: {
        std::string index = alloc_temp16();
        std::string t = alloc_temp16();
        emit_expr(*s.let_stmt->index, index);
        emit_expr(s.let_stmt->expr, t);
        emit("put_array16(" + var + ", " + index + ", " + t + ")");
        free_temp16(index);
        free_temp16(t);
        break;
    }
    case LetType::String: {
        if (s.let_stmt->expr.expr_type == ExprType::StringLiteral) {
            const std::string& str = s.let_stmt->expr.string_value;
            emit("set_string(" + var + ", \"" + escape(str) + "\")");
        }
        else {
            int size = s.let_stmt->expr.string_size;
            std::string t = alloc_temp_string(size);
            emit_expr(s.let_stmt->expr, t);
            emit("set_string(" + var + ", " + t + ")");
            free_temp_string(t);
        }
        break;
    }
    default:
        assert(0);
    }
}

void CodeGen::emit_dim(const Stmt&) {
}

void CodeGen::emit_if(const Stmt& s) {
    const IfStmt& stmt_if = *s.if_stmt;

    // 1. Evaluate condition into a temp cell
    std::string cond = alloc_temp16();
    emit_expr(stmt_if.condition, cond);

    // 2. Begin IF
    emit("if(" + cond + ")");

    // 3. THEN block
    for (auto& stmt : stmt_if.then_block.statements) {
        emit_stmt(*stmt);
    }

    // 4. ELSE block (optional)
    if (!stmt_if.else_block.statements.empty()) {
        emit("else");
        for (auto& stmt : stmt_if.else_block.statements) {
            emit_stmt(*stmt);
        }
    }

    // 5. ENDIF
    emit("endif");

    // 6. Free temp
    free_temp16(cond);
}

void CodeGen::emit_while(const Stmt& s) {
    const WhileStmt& stmt_while = *s.while_stmt;

    // 1. Allocate temp for condition
    std::string cond = alloc_temp16();

    // 2. Initial evaluation
    emit_expr(stmt_while.condition, cond);

    // 3. While header
    emit("while(" + cond + ")");

    // 4. Body
    for (auto& stmt : stmt_while.body.statements) {
        emit_stmt(*stmt);
    }

    // 5. Re-evaluate condition at loop bottom
    emit_expr(stmt_while.condition, cond);

    // 6. End of loop
    emit("endwhile");

    // 7. Free temp
    free_temp16(cond);
}

void CodeGen::emit_for(const Stmt& s) {
    const ForStmt& f = *s.for_stmt;

    // Allocate temps
    std::string t_start = alloc_temp16();
    std::string t_end = alloc_temp16();
    std::string t_step = alloc_temp16();
    std::string t_cond = alloc_temp16();

    // Evaluate start, end, step
    emit_expr(f.start_expr, t_start);
    emit_expr(f.end_expr, t_end);
    emit_expr(f.step_expr, t_step);

    // Initialize loop variable
    emit("copy16(" + t_start + ", " + f.var + ")");

    // Lambda to compute loop continuation condition
    auto compute_condition = [&]() {
        emit("copy16(" + t_step + ", " + t_cond + ")");
        emit("sign16(" + t_cond + ")");
        emit("if(" + t_cond + ")");
        emit("copy16(" + f.var + ", " + t_cond + ")");
        emit("ge16s(" + t_cond + ", " + t_end + ")");
        emit("else");
        emit("copy16(" + f.var + ", " + t_cond + ")");
        emit("le16s(" + t_cond + ", " + t_end + ")");
        emit("endif");
    };

    // Compute initial condition
    compute_condition();

    // WHILE
    emit("while(" + t_cond + ")");

    // Body
    for (auto& stmt : f.body.statements) {
        emit_stmt(*stmt);
    }

    // Increment
    emit("add16s(" + f.var + ", " + t_step + ")");

    // Recompute condition
    compute_condition();

    emit("endwhile");

    // Free temps
    free_temp16(t_start);
    free_temp16(t_end);
    free_temp16(t_step);
    free_temp16(t_cond);
}

// expr result goes into target
void CodeGen::emit_expr(const Expr& e, const std::string& target) {
    switch (e.expr_type) {
    case ExprType::Number:
        emit("set16(" + target + ", " + std::to_string(e.int_value) + ")");
        break;

    case ExprType::Var:
        emit("copy16(" + e.name + ", " + target + ")");
        break;

    case ExprType::BinOp:
        emit_binary(e, target);
        break;

    case ExprType::UnaryOp:
        emit_unary(e, target);
        break;

    case ExprType::ArrayAccess: {
        std::string index = alloc_temp16();
        emit_expr(*e.index, index);
        emit("get_array16(" + e.name + ", " + index + ", " + target + ")");
        free_temp16(index);
        break;
    }
    case ExprType::StringLiteral: {
        emit("set_string(" + target + ", \"" +
             escape(e.string_value) + "\")");
        break;
    }
    case ExprType::Concat: {
        std::string left = alloc_temp_string(e.left->string_size);
        std::string right = alloc_temp_string(e.right->string_size);
        emit_expr(*e.left, left);
        emit_expr(*e.right, right);
        emit("set_string(" + target + ", " + left + ")");
        emit("append_string(" + target + ", " + right + ")");
        free_temp_string(left);
        free_temp_string(right);
        break;
    }
    case ExprType::Call: {
        emit_call(e, target);
        break;
    }
    default:
        assert(0);
    }
}

void CodeGen::emit_unary(const Expr& e, const std::string& target) {
    // Evaluate inner into target
    emit_expr(*e.inner, target);

    switch (e.op) {
    case TokenType::Plus:
        // no-op
        break;

    case TokenType::Minus:
        emit("neg16(" + target + ")");
        break;

    case TokenType::KeywordNot:
        // NOT x  ->  (x == 0)
        emit("not16(" + target + ")");
        break;

    default:
        assert(0);
    }
}

void CodeGen::emit_binary(const Expr& e, const std::string& target) {
    // Evaluate left into target
    emit_expr(*e.left, target);

    // Evaluate right into a temp
    std::string tmp = alloc_temp16();
    emit_expr(*e.right, tmp);

    switch (e.op) {

    // Arithmetic
    case TokenType::Plus:
        emit("add16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Minus:
        emit("sub16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Star:
        emit("mul16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Slash:
        emit("div16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::KeywordMod:
        emit("mod16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Caret:
        emit("pow16s(" + target + ", " + tmp + ")");
        break;

    // Shifts
    case TokenType::KeywordShl:
        emit("shl16(" + target + ", " + tmp + ")");
        break;
    case TokenType::KeywordShr:
        emit("shr16(" + target + ", " + tmp + ")");
        break;

    // Relational (normalize to 0/1)
    case TokenType::Equal:
        emit("eq16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::NotEqual:
        emit("ne16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Less:
        emit("lt16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::LessEqual:
        emit("le16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::Greater:
        emit("gt16s(" + target + ", " + tmp + ")");
        break;
    case TokenType::GreaterEqual:
        emit("ge16s(" + target + ", " + tmp + ")");
        break;

    // Boolean logic (operates on 0/1)
    case TokenType::KeywordAnd:
        emit("and16(" + target + ", " + tmp + ")");
        break;
    case TokenType::KeywordOr:
        emit("or16(" + target + ", " + tmp + ")");
        break;
    case TokenType::KeywordXor:
        emit("xor16(" + target + ", " + tmp + ")");
        break;

    default:
        assert(0);
    }

    free_temp16(tmp);
}

void CodeGen::emit_call(const Expr& e, const std::string& target) {
    switch (e.func) {
    case TokenType::KeywordLeftDollar: {
        assert(e.args.size() == 2);

        std::string arg0 = alloc_temp_string(e.args[0]->string_size);
        emit_expr(*e.args[0], arg0);   // string

        std::string arg1 = alloc_temp16();
        emit_expr(*e.args[1], arg1);     // length

        emit("left_string(" + target + ", " + arg0 + ", " + arg1 + ")");

        free_temp_string(arg0);
        free_temp16(arg1);
        break;
    }
    case TokenType::KeywordRightDollar: {
        assert(e.args.size() == 2);

        std::string arg0 = alloc_temp_string(e.args[0]->string_size);
        emit_expr(*e.args[0], arg0);   // string

        std::string arg1 = alloc_temp16();
        emit_expr(*e.args[1], arg1);     // length

        emit("right_string(" + target + ", " + arg0 + ", " + arg1 + ")");

        free_temp_string(arg0);
        free_temp16(arg1);
        break;
    }
    case TokenType::KeywordMidDollar: {
        assert(e.args.size() == 3);

        std::string arg0 = alloc_temp_string(e.args[0]->string_size);
        emit_expr(*e.args[0], arg0);   // string

        std::string arg1 = alloc_temp16();
        emit_expr(*e.args[1], arg1);     // start

        std::string arg2 = alloc_temp16();
        emit_expr(*e.args[2], arg2);     // length

        emit("mid_string(" + target + ", " + arg0 + ", " +
             arg1 + ", " + arg2 + ")");

        free_temp_string(arg0);
        free_temp16(arg1);
        free_temp16(arg2);
        break;
    }
    default:
        assert(0);
    }
}
