#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

spew("$test.bas", <<'END');
DIM A(2)
LET A(1) = 2
LET A(2) = 4
PRINT A(1);A(2);
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array16(A, 3)
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
set16(_BFB1, 1)
set16(_BFB2, 2)
put_array16(A, _BFB1, _BFB2)
free_cell16(_BFB1)
free_cell16(_BFB2)
alloc_cell16(_BFB3)
alloc_cell16(_BFB4)
set16(_BFB3, 2)
set16(_BFB4, 4)
put_array16(A, _BFB3, _BFB4)
free_cell16(_BFB3)
free_cell16(_BFB4)
alloc_cell16(_BFB5)
alloc_cell16(_BFB6)
set16(_BFB6, 1)
get_array16(A, _BFB6, _BFB5)
free_cell16(_BFB6)
print_cell16s(_BFB5)
free_cell16(_BFB5)
alloc_cell16(_BFB7)
alloc_cell16(_BFB8)
set16(_BFB8, 2)
get_array16(A, _BFB8, _BFB7)
free_cell16(_BFB8)
print_cell16s(_BFB7)
free_cell16(_BFB7)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "2 4 ");

spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = "Hello World!"
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
set_string(A$, "Hello World!")
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "Hello World!");

spew("$test.bas", <<'END');
DIM A(2), B(2)
LET A(1) = 2
LET A(2) = 4
LET B(1) = 3
LET B(2) = 6
PRINT A(1);A(2);B(1);B(2);
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array16(A, 3)
alloc_array16(B, 3)
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
set16(_BFB1, 1)
set16(_BFB2, 2)
put_array16(A, _BFB1, _BFB2)
free_cell16(_BFB1)
free_cell16(_BFB2)
alloc_cell16(_BFB3)
alloc_cell16(_BFB4)
set16(_BFB3, 2)
set16(_BFB4, 4)
put_array16(A, _BFB3, _BFB4)
free_cell16(_BFB3)
free_cell16(_BFB4)
alloc_cell16(_BFB5)
alloc_cell16(_BFB6)
set16(_BFB5, 1)
set16(_BFB6, 3)
put_array16(B, _BFB5, _BFB6)
free_cell16(_BFB5)
free_cell16(_BFB6)
alloc_cell16(_BFB7)
alloc_cell16(_BFB8)
set16(_BFB7, 2)
set16(_BFB8, 6)
put_array16(B, _BFB7, _BFB8)
free_cell16(_BFB7)
free_cell16(_BFB8)
alloc_cell16(_BFB9)
alloc_cell16(_BFB10)
set16(_BFB10, 1)
get_array16(A, _BFB10, _BFB9)
free_cell16(_BFB10)
print_cell16s(_BFB9)
free_cell16(_BFB9)
alloc_cell16(_BFB11)
alloc_cell16(_BFB12)
set16(_BFB12, 2)
get_array16(A, _BFB12, _BFB11)
free_cell16(_BFB12)
print_cell16s(_BFB11)
free_cell16(_BFB11)
alloc_cell16(_BFB13)
alloc_cell16(_BFB14)
set16(_BFB14, 1)
get_array16(B, _BFB14, _BFB13)
free_cell16(_BFB14)
print_cell16s(_BFB13)
free_cell16(_BFB13)
alloc_cell16(_BFB15)
alloc_cell16(_BFB16)
set16(_BFB16, 2)
get_array16(B, _BFB16, _BFB15)
free_cell16(_BFB16)
print_cell16s(_BFB15)
free_cell16(_BFB15)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "2 4 3 6 ");

unlink_testfiles;
done_testing;
