#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# INPUT
spew("$test.bas", <<END);
INPUT
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Parse error at line 2, column 1: Expected variable name after INPUT
END

# INPUT A,
spew("$test.bas", <<END);
INPUT A,
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Parse error at line 2, column 1: Expected variable name after ,
END

# INPUT A
spew("$test.bas", <<END);
INPUT A
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
scan_cell16s(A)
END
run_ok("bfpp $test.bfpp > $test.bf");
capture_ok("echo 10 | bf -D $test.bf", <<END);
Tape: 10   0   0   0   0   0   0   0   0  10 
     ^^^ (ptr=0)

END

# INPUT A, B
spew("$test.bas", <<END);
INPUT A, B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
scan_cell16s(A)
scan_cell16s(B)
END
run_ok("bfpp $test.bfpp > $test.bf");
capture_ok("echo 10 20 | bf -D $test.bf", <<END);
Tape: 10   0  20   0   0   0   0   0   0   0   0  10 
     ^^^ (ptr=0)

END

unlink_testfiles;
done_testing;
