#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# single PRINT
spew("$test.bas", <<END);
PRINT
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "\n");

# single PRINT ;
spew("$test.bas", <<END);
PRINT ;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
END
capture_ok("bfpp $test.bfpp | bf", "");

# single PRINT ,
spew("$test.bas", <<END);
PRINT ,
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
print_char(9)
END
capture_ok("bfpp $test.bfpp | bf", "\t");

# PRINT 25
spew("$test.bas", <<END);
PRINT 25
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(_BFB1)
set16(_BFB1, 25)
print_cell16s(_BFB1)
free_cell16(_BFB1)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "25 \n");

# PRINT 25;
spew("$test.bas", <<END);
PRINT 25;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(_BFB1)
set16(_BFB1, 25)
print_cell16s(_BFB1)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf", "25 ");

# PRINT 5*5;
spew("$test.bas", <<END);
PRINT 5*5;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(_BFB1)
set16(_BFB1, 25)
print_cell16s(_BFB1)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf", "25 ");

# PRINT "hello ""world"""
spew("$test.bas", <<END);
PRINT "hello ""world"""
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
print_string("hello \"world\"")
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "hello \"world\"\n");

# PRINT "hello " & "world"
spew("$test.bas", <<END);
PRINT "hello " & "world"
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(_BFB1$, 12)
set_string(_BFB1$, "hello world")
print_string(_BFB1$)
free_array8(_BFB1$)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "hello world\n");

# PRINT V;
spew("$test.bas", <<END);
PRINT V;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(V)
print_cell16s(V)
END
capture_ok("bfpp $test.bfpp | bf", "0 ");

# PRINT V
spew("$test.bas", <<END);
PRINT V
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(V)
print_cell16s(V)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "0 \n");

# PRINT "V=";1+2+3
spew("$test.bas", <<END);
PRINT "V=";1+2+3
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
print_string("V=")
alloc_cell16(_BFB1)
set16(_BFB1, 6)
print_cell16s(_BFB1)
free_cell16(_BFB1)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "V=6 \n");

# PRINT "V=",,1+2+3
spew("$test.bas", <<END);
PRINT "V=",,1+2+3
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END'); # Note quoted 'END'
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
print_string("V=")
print_char(9)
print_char(9)
alloc_cell16(_BFB1)
set16(_BFB1, 6)
print_cell16s(_BFB1)
free_cell16(_BFB1)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", "V=\t\t6 \n");

unlink_testfiles;
done_testing;
