#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# subroutine not defined
spew("$test.bas", <<'END');
say_hi(2, "Doe")
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: undefined subroutine 'SAY_HI'
END

# subroutine multiply defined
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: subroutine 'SAY_HI' already defined
END

# wrong number of arguments
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 5: Expected '(' after subroutine name
END

spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
say_hi
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: Expected LET, INPUT, PRINT, IF, WHILE, FOR, DIM or CALL
END

spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi()
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: subroutine 'SAY_HI' expects 2 argument(s), got 0
END

spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi(1)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: subroutine 'SAY_HI' expects 2 argument(s), got 1
END

spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi(1, "", 3)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: subroutine 'SAY_HI' expects 2 argument(s), got 3
END

# wrong type of arguments
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi("hello", "world")
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: argument 1 of 'SAY_HI' expects integer but got string
END

spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	PRINT N; N$
ENDSUB
CALL say_hi(1, 2)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: argument 2 of 'SAY_HI' expects string but got integer
END

# check recursion
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	IF N > 0 THEN
		say_hi(N-1, N$)
		PRINT N; N$
	ENDIF
ENDSUB
say_hi(1, "John")
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 3: subroutine 'SAY_HI' cannot call itself (recursion is not supported)
END

# check returning of values
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	say_hi = N + LEN(N$)
ENDSUB
say_hi(1, "John")
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 2: cannot assign to subroutine name 'SAY_HI' (subroutines return void)
END

# check duplicate names variable and sub
spew("$test.bas", <<'END');
hello = 3
SUB hello()
ENDSUB
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

spew("$test.bas", <<'END');
DIM hello(3)
SUB hello()
ENDSUB
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

spew("$test.bas", <<'END');
LET A = hello ^ 2
SUB hello()
ENDSUB
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

# SUB call with inlining and use of global vars
spew("$test.bas", <<'END');
SUB say_hi(N, N$)
	DIM A$(10)
	G = G + N
	A$ = "hi " & N$ & "!"
	PRINT G; A$
ENDSUB

CALL say_hi(1, "John")
say_hi(2, "Doe")
PRINT G
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(G)
alloc_array8(SAY_HI_1_A$, 11)
alloc_cell16(SAY_HI_1_N)
alloc_array8(SAY_HI_1_N$, 5)
alloc_array8(SAY_HI_2_A$, 11)
alloc_cell16(SAY_HI_2_N)
alloc_array8(SAY_HI_2_N$, 4)
set16(SAY_HI_1_N, 1)
set_string(SAY_HI_1_N$, "John")
alloc_cell16(_BFB1)
copy16(G, _BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 1)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, G)
free_cell16(_BFB1)
set_string(SAY_HI_1_A$, "hi John!")
print_cell16s(G)
print_string(SAY_HI_1_A$)
print_newline
set16(SAY_HI_2_N, 2)
set_string(SAY_HI_2_N$, "Doe")
alloc_cell16(_BFB3)
copy16(G, _BFB3)
alloc_cell16(_BFB4)
set16(_BFB4, 2)
add16s(_BFB3, _BFB4)
free_cell16(_BFB4)
move16(_BFB3, G)
free_cell16(_BFB3)
set_string(SAY_HI_2_A$, "hi Doe!")
print_cell16s(G)
print_string(SAY_HI_2_A$)
print_newline
print_cell16s(G)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", <<'END');
1 hi John!
3 hi Doe!
3 
END

# inlining in two levels
spew("$test.bas", <<'END');
SUB s1(a, b)
	s2(a + b)
	s2(a - b)
ENDSUB
SUB s2(n)
	G = G + n^2
ENDSUB
s1(2, 4)
PRINT G
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(G)
alloc_cell16(S1_1_A)
alloc_cell16(S1_1_B)
alloc_cell16(S2_1_N)
alloc_cell16(S2_2_N)
set16(S1_1_A, 2)
set16(S1_1_B, 4)
set16(S2_1_N, 6)
alloc_cell16(_BFB1)
copy16(G, _BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 36)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, G)
free_cell16(_BFB1)
set16(S2_2_N, -2)
alloc_cell16(_BFB3)
copy16(G, _BFB3)
alloc_cell16(_BFB4)
set16(_BFB4, 4)
add16s(_BFB3, _BFB4)
free_cell16(_BFB4)
move16(_BFB3, G)
free_cell16(_BFB3)
print_cell16s(G)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", <<'END');
40 
END

# test inlining when arguments are not constant
spew("$test.bas", <<'END');
DIM A$(10)
SUB say_hi(A$)
	PRINT "Hello " & A$ & "!"
ENDSUB
INPUT A$
say_hi(A$)
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 11)
alloc_array8(SAY_HI_1_A$, 11)
scan_word(A$)
alloc_array8(_BFB1$, 11)
set_string(_BFB1$, A$)
set_string(SAY_HI_1_A$, _BFB1$)
free_array8(_BFB1$)
alloc_array8(_BFB2$, 18)
alloc_array8(_BFB3$, 17)
alloc_array8(_BFB4$, 7)
set_string(_BFB4$, "Hello ")
set_string(_BFB3$, _BFB4$)
append_string(_BFB3$, SAY_HI_1_A$)
free_array8(_BFB4$)
alloc_array8(_BFB5$, 2)
set_string(_BFB5$, "!")
set_string(_BFB2$, _BFB3$)
append_string(_BFB2$, _BFB5$)
free_array8(_BFB3$)
free_array8(_BFB5$)
print_string(_BFB2$)
free_array8(_BFB2$)
print_newline
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("echo John | bf $test.bf", <<'END');
Hello John!
END

unlink_testfiles;
done_testing;
