#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# & with literal strings
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = "Hello " & "World!"
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 13)
alloc_array8(_BFB2$, 7)
set_string(_BFB2$, "Hello ")
alloc_array8(_BFB3$, 7)
set_string(_BFB3$, "World!")
set_string(_BFB1$, _BFB2$)
append_string(_BFB1$, _BFB3$)
free_array8(_BFB2$)
free_array8(_BFB3$)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "Hello World!");

# & with variable strings
spew("$test.bas", <<'END');
DIM A$(12) : DIM B$(12) : DIM C$(12)
LET A$ = "Hello "
LET B$ = "World!"
LET C$ = A$ & B$
PRINT C$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(B$, 13)
alloc_array8(C$, 13)
set_string(A$, "Hello ")
set_string(B$, "World!")
alloc_array8(_BFB1$, 25)
set_string(_BFB1$, A$)
append_string(_BFB1$, B$)
set_string(C$, _BFB1$)
free_array8(_BFB1$)
print_string(C$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "Hello World!");

# LEFT$ literal string
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = LEFT$("Hello World!", 5)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 13)
alloc_array8(_BFB2$, 13)
set_string(_BFB2$, "Hello World!")
alloc_cell16(_BFB3)
set16(_BFB3, 5)
left_string(_BFB1$, _BFB2$, _BFB3)
free_array8(_BFB2$)
free_cell16(_BFB3)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "Hello");

# LEFT$ variable string
spew("$test.bas", <<'END');
DIM A$(12) : DIM B$(12)
LET A$ = "Hello World!"
LET B$ = LEFT$(A$, 5)
PRINT B$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(B$, 13)
set_string(A$, "Hello World!")
alloc_array8(_BFB1$, 13)
alloc_cell16(_BFB2)
set16(_BFB2, 5)
left_string(_BFB1$, A$, _BFB2)
free_cell16(_BFB2)
set_string(B$, _BFB1$)
free_array8(_BFB1$)
print_string(B$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "Hello");

# RIGHT$ literal string
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = RIGHT$("Hello World!", 6)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 13)
alloc_array8(_BFB2$, 13)
set_string(_BFB2$, "Hello World!")
alloc_cell16(_BFB3)
set16(_BFB3, 6)
right_string(_BFB1$, _BFB2$, _BFB3)
free_array8(_BFB2$)
free_cell16(_BFB3)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "World!");

# RIGHT$ variable string
spew("$test.bas", <<'END');
DIM A$(12) : DIM B$(12)
LET A$ = "Hello World!"
LET B$ = RIGHT$(A$, 6)
PRINT B$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(B$, 13)
set_string(A$, "Hello World!")
alloc_array8(_BFB1$, 13)
alloc_cell16(_BFB2)
set16(_BFB2, 6)
right_string(_BFB1$, A$, _BFB2)
free_cell16(_BFB2)
set_string(B$, _BFB1$)
free_array8(_BFB1$)
print_string(B$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "World!");

# MID$ literal string
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = MID$("Hello World!", 7, 5)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 13)
alloc_array8(_BFB2$, 13)
set_string(_BFB2$, "Hello World!")
alloc_cell16(_BFB3)
set16(_BFB3, 7)
alloc_cell16(_BFB4)
set16(_BFB4, 5)
mid_string(_BFB1$, _BFB2$, _BFB3, _BFB4)
free_array8(_BFB2$)
free_cell16(_BFB3)
free_cell16(_BFB4)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "World");

# MID$ variable string
spew("$test.bas", <<'END');
DIM A$(12) : DIM B$(12)
LET A$ = "Hello World!"
LET B$ = MID$(A$, 7, 5)
PRINT B$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(B$, 13)
set_string(A$, "Hello World!")
alloc_array8(_BFB1$, 13)
alloc_cell16(_BFB2)
set16(_BFB2, 7)
alloc_cell16(_BFB3)
set16(_BFB3, 5)
mid_string(_BFB1$, A$, _BFB2, _BFB3)
free_cell16(_BFB2)
free_cell16(_BFB3)
set_string(B$, _BFB1$)
free_array8(_BFB1$)
print_string(B$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "World");

# STR$
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = STR$(-32768)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 8)
alloc_cell16(_BFB2)
set16(_BFB2, -32768)
format_cell16s(_BFB1$, _BFB2)
free_cell16(_BFB2)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "-32768 ");

# STR$
spew("$test.bas", <<'END');
LET A=1 ' prevent constant folding
DIM A$(12)
LET A = -32768
LET A$ = STR$(A)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set16(A, 1)
set16(A, -32768)
alloc_array8(_BFB1$, 8)
format_cell16s(_BFB1$, A)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "-32768 ");

# LEN
spew("$test.bas", <<'END');
LET A = LEN("Hello")
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(_BFB1)
alloc_array8(_BFB2$, 6)
set_string(_BFB2$, "Hello")
alloc_cell16(_BFB3)
set16(_BFB3, 0)
get_array8(_BFB2$, _BFB3, _BFB1)
free_cell16(_BFB3)
free_array8(_BFB2$)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "5 ");

# LEN
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = "Hello"
LET A = LEN(A$)
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set_string(A$, "Hello")
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 0)
get_array8(A$, _BFB2, _BFB1)
free_cell16(_BFB2)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "5 ");

# VAL
spew("$test.bas", <<'END');
LET A = VAL("-12345")
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(_BFB1)
alloc_array8(_BFB2$, 7)
set_string(_BFB2$, "-12345")
string_val16s(_BFB2$, _BFB1)
free_array8(_BFB2$)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "-12345 ");

# VAL
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = "-12345"
LET A = VAL(A$)
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set_string(A$, "-12345")
alloc_cell16(_BFB1)
string_val16s(A$, _BFB1)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "-12345 ");

# CHR$
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = CHR$(33)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 13)
alloc_array8(_BFB1$, 2)
alloc_cell16(_BFB2)
set16(_BFB2, 33)
alloc_cell16(_BFB3)
set16(_BFB3, 0)
alloc_cell16(_BFB4)
set16(_BFB4, 1)
put_array8(_BFB1$, _BFB3, _BFB4)
put_array8(_BFB1$, _BFB4, _BFB2)
free_cell16(_BFB3)
free_cell16(_BFB4)
free_cell16(_BFB2)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "!");

# CHR$
spew("$test.bas", <<'END');
LET A = 1 ' prevent constant folding
DIM A$(12)
LET A = 33
LET A$ = CHR$(A)
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set16(A, 1)
set16(A, 33)
alloc_array8(_BFB1$, 2)
alloc_cell16(_BFB2)
set16(_BFB2, 0)
alloc_cell16(_BFB3)
set16(_BFB3, 1)
put_array8(_BFB1$, _BFB2, _BFB3)
put_array8(_BFB1$, _BFB3, A)
free_cell16(_BFB2)
free_cell16(_BFB3)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "!");

# ASC
spew("$test.bas", <<'END');
LET A = ASC("")
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(_BFB1)
alloc_array8(_BFB2$, 1)
set_string(_BFB2$, "")
alloc_cell16(_BFB3)
set16(_BFB3, 0)
alloc_cell16(_BFB4)
set16(_BFB4, 1)
alloc_cell16(_BFB5)
get_array8(_BFB2$, _BFB3, _BFB5)
if(_BFB5)
get_array8(_BFB2$, _BFB4, _BFB1)
else
set16(_BFB1, 0)
endif
free_cell16(_BFB3)
free_cell16(_BFB4)
free_cell16(_BFB5)
free_array8(_BFB2$)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "0 ");

# ASC
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = ""
LET A = ASC(A$)
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set_string(A$, "")
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 0)
alloc_cell16(_BFB3)
set16(_BFB3, 1)
alloc_cell16(_BFB4)
get_array8(A$, _BFB2, _BFB4)
if(_BFB4)
get_array8(A$, _BFB3, _BFB1)
else
set16(_BFB1, 0)
endif
free_cell16(_BFB2)
free_cell16(_BFB3)
free_cell16(_BFB4)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "0 ");

# ASC
spew("$test.bas", <<'END');
LET A = ASC("!")
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(_BFB1)
alloc_array8(_BFB2$, 2)
set_string(_BFB2$, "!")
alloc_cell16(_BFB3)
set16(_BFB3, 0)
alloc_cell16(_BFB4)
set16(_BFB4, 1)
alloc_cell16(_BFB5)
get_array8(_BFB2$, _BFB3, _BFB5)
if(_BFB5)
get_array8(_BFB2$, _BFB4, _BFB1)
else
set16(_BFB1, 0)
endif
free_cell16(_BFB3)
free_cell16(_BFB4)
free_cell16(_BFB5)
free_array8(_BFB2$)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "33 ");

# ASC
spew("$test.bas", <<'END');
DIM A$(12)
LET A$ = "!"
LET A = ASC(A$)
PRINT A;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_array8(A$, 13)
set_string(A$, "!")
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 0)
alloc_cell16(_BFB3)
set16(_BFB3, 1)
alloc_cell16(_BFB4)
get_array8(A$, _BFB2, _BFB4)
if(_BFB4)
get_array8(A$, _BFB3, _BFB1)
else
set16(_BFB1, 0)
endif
free_cell16(_BFB2)
free_cell16(_BFB3)
free_cell16(_BFB4)
move16(_BFB1, A)
free_cell16(_BFB1)
print_cell16s(A)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "33 ");

# self-referencing expression
spew("$test.bas", <<'END');
DIM A$(16)
LET A$ = "Hello "
LET A$ = " " & A$ & A$
PRINT A$;
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 17)
set_string(A$, "Hello ")
alloc_array8(_BFB1$, 34)
alloc_array8(_BFB2$, 18)
alloc_array8(_BFB3$, 2)
set_string(_BFB3$, " ")
set_string(_BFB2$, _BFB3$)
append_string(_BFB2$, A$)
free_array8(_BFB3$)
set_string(_BFB1$, _BFB2$)
append_string(_BFB1$, A$)
free_array8(_BFB2$)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", " Hello Hello ");

unlink_testfiles;
done_testing;
