#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# LET v = number
spew("$test.bas", <<END);
LET A = 10
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
set16(A, 10)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10 
     ^^^ (ptr=0)

END

# LET v = string
spew("$test.bas", <<END);
LET A = "hello"
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: cannot assign string to number variable 'A'
END

# LET v = var
spew("$test.bas", <<END);
LET A = 1 ' prevent constant folding
LET A = 10
LET B = A
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
set16(A, 1)
set16(A, 10)
copy16(A, B)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0  10 
     ^^^ (ptr=0)

END

# v = number
spew("$test.bas", <<END);
A = 10
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
set16(A, 10)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10 
     ^^^ (ptr=0)

END

# v = var
spew("$test.bas", <<END);
A = 1 ' prevent constant folding
A = 10
B = A
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
set16(A, 1)
set16(A, 10)
copy16(A, B)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0  10 
     ^^^ (ptr=0)

END

# LET A(1) = expr
spew("$test.bas", <<END);
LET A(1) = 10
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: array 'A' must be declared by DIM before used
END

# A(1) = expr
spew("$test.bas", <<END);
A(1) = 10
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: array 'A' must be declared by DIM before used
END

# LET A = 3: LET A(1) = expr
spew("$test.bas", <<END);
LET A = 3
LET A(1) = 10
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 2: variable 'A' is not an array
END

# A = 3: A(1) = expr
spew("$test.bas", <<END);
A = 3
A(1) = 10
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 2: variable 'A' is not an array
END

# Test arrays
spew("$test.bas", <<END);
DIM A(4)
FOR I = 1 TO 4
	A(I) = I+I
NEXT I
FOR I = 4 TO 1 STEP -1
	PRINT A(I);
NEXT I
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array16(A, 5)
alloc_cell16(I)
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
alloc_cell16(_BFB3)
alloc_cell16(_BFB4)
set16(_BFB1, 1)
set16(_BFB2, 4)
set16(_BFB3, 1)
copy16(_BFB1, I)
copy16(_BFB3, _BFB4)
sign16(_BFB4)
if(_BFB4)
copy16(I, _BFB4)
ge16s(_BFB4, _BFB2)
else
copy16(I, _BFB4)
le16s(_BFB4, _BFB2)
endif
while(_BFB4)
alloc_cell16(_BFB5)
alloc_cell16(_BFB6)
copy16(I, _BFB5)
copy16(I, _BFB6)
add16s(_BFB6, I)
put_array16(A, _BFB5, _BFB6)
free_cell16(_BFB5)
free_cell16(_BFB6)
add16s(I, _BFB3)
copy16(_BFB3, _BFB4)
sign16(_BFB4)
if(_BFB4)
copy16(I, _BFB4)
ge16s(_BFB4, _BFB2)
else
copy16(I, _BFB4)
le16s(_BFB4, _BFB2)
endif
endwhile
free_cell16(_BFB1)
free_cell16(_BFB2)
free_cell16(_BFB3)
free_cell16(_BFB4)
alloc_cell16(_BFB7)
alloc_cell16(_BFB8)
alloc_cell16(_BFB9)
alloc_cell16(_BFB10)
set16(_BFB7, 4)
set16(_BFB8, 1)
set16(_BFB9, -1)
copy16(_BFB7, I)
copy16(_BFB9, _BFB10)
sign16(_BFB10)
if(_BFB10)
copy16(I, _BFB10)
ge16s(_BFB10, _BFB8)
else
copy16(I, _BFB10)
le16s(_BFB10, _BFB8)
endif
while(_BFB10)
alloc_cell16(_BFB11)
alloc_cell16(_BFB12)
copy16(I, _BFB12)
get_array16(A, _BFB12, _BFB11)
free_cell16(_BFB12)
print_cell16s(_BFB11)
free_cell16(_BFB11)
add16s(I, _BFB9)
copy16(_BFB9, _BFB10)
sign16(_BFB10)
if(_BFB10)
copy16(I, _BFB10)
ge16s(_BFB10, _BFB8)
else
copy16(I, _BFB10)
le16s(_BFB10, _BFB8)
endif
endwhile
free_cell16(_BFB7)
free_cell16(_BFB8)
free_cell16(_BFB9)
free_cell16(_BFB10)
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("bf $test.bf", "8 6 4 2 ");

# LET A$... without DIM
spew("$test.bas", <<'END');
LET A$ = "hello"
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 1: string variable 'A$' must be declared by DIM before used
END

# LET A$ = number
spew("$test.bas", <<'END');
DIM A$(10)
LET A$ = 10
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 2: cannot assign number to string variable 'A$'
END

# LET A$ = string
spew("$test.bas", <<'END');
DIM A$(10)
LET A$ = "hello"
PRINT A$;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 11)
set_string(A$, "hello")
print_string(A$)
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("bf $test.bf", "hello");

# LET A$ = string & string
spew("$test.bas", <<'END');
DIM A$(11)
LET A$ = "hello" & " " & "world"
PRINT A$;
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 12)
alloc_array8(_BFB1$, 12)
alloc_array8(_BFB2$, 7)
alloc_array8(_BFB3$, 6)
set_string(_BFB3$, "hello")
alloc_array8(_BFB4$, 2)
set_string(_BFB4$, " ")
set_string(_BFB2$, _BFB3$)
append_string(_BFB2$, _BFB4$)
free_array8(_BFB3$)
free_array8(_BFB4$)
alloc_array8(_BFB5$, 6)
set_string(_BFB5$, "world")
set_string(_BFB1$, _BFB2$)
append_string(_BFB1$, _BFB5$)
free_array8(_BFB2$)
free_array8(_BFB5$)
set_string(A$, _BFB1$)
free_array8(_BFB1$)
print_string(A$)
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("bf $test.bf", "hello world");

unlink_testfiles;
done_testing;
