#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# LET v = number
spew("$test.bas", <<END);
LET A = 10
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
set16(A, 10)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10 
     ^^^ (ptr=0)

END

# LET v = var
spew("$test.bas", <<END);
LET A = 10
LET B = A
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
set16(A, 10)
copy16(A, B)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0  10 
     ^^^ (ptr=0)

END

# v = number
spew("$test.bas", <<END);
A = 10
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
set16(A, 10)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10 
     ^^^ (ptr=0)

END

# v = var
spew("$test.bas", <<END);
A = 10
B = A
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
set16(A, 10)
copy16(A, B)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0  10 
     ^^^ (ptr=0)

END

# LET A(1) = expr
spew("$test.bas", <<END);
LET A(1) = 10
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Error at line 1: array 'A' must be declared by DIM before used
END

# A(1) = expr
spew("$test.bas", <<END);
A(1) = 10
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Error at line 1: array 'A' must be declared by DIM before used
END

# LET A = 3: LET A(1) = expr
spew("$test.bas", <<END);
LET A = 3
LET A(1) = 10
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Error at line 2: variable 'A' is not an array
END

# A = 3: A(1) = expr
spew("$test.bas", <<END);
A = 3
A(1) = 10
END
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Error at line 2: variable 'A' is not an array
END

# Test arrays
spew("$test.bas", <<END);
DIM A(4)
FOR I = 1 TO 4
	A(I) = I+I
NEXT I
FOR I = 4 TO 1 STEP -1
	PRINT A(I);
NEXT I
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array16(A, 5)
alloc_cell16(I)
alloc_cell16(_BFB1)
alloc_cell16(_BFB2)
alloc_cell16(_BFB3)
alloc_cell16(_BFB4)
set16(_BFB1, 1)
set16(_BFB2, 4)
set16(_BFB3, 1)
copy16(_BFB1, I)
copy16(_BFB3, _BFB4)
sign16(_BFB4)
if(_BFB4)
copy16(I, _BFB4)
ge16s(_BFB4, _BFB2)
else
copy16(I, _BFB4)
le16s(_BFB4, _BFB2)
endif
while(_BFB4)
alloc_cell16(_BFB5)
alloc_cell16(_BFB6)
copy16(I, _BFB5)
copy16(I, _BFB6)
alloc_cell16(_BFB7)
copy16(I, _BFB7)
add16s(_BFB6, _BFB7)
free_cell16(_BFB7)
put_array16(A, _BFB5, _BFB6)
free_cell16(_BFB5)
free_cell16(_BFB6)
add16s(I, _BFB3)
copy16(_BFB3, _BFB4)
sign16(_BFB4)
if(_BFB4)
copy16(I, _BFB4)
ge16s(_BFB4, _BFB2)
else
copy16(I, _BFB4)
le16s(_BFB4, _BFB2)
endif
endwhile
free_cell16(_BFB1)
free_cell16(_BFB2)
free_cell16(_BFB3)
free_cell16(_BFB4)
alloc_cell16(_BFB8)
alloc_cell16(_BFB9)
alloc_cell16(_BFB10)
alloc_cell16(_BFB11)
set16(_BFB8, 4)
set16(_BFB9, 1)
set16(_BFB10, -1)
copy16(_BFB8, I)
copy16(_BFB10, _BFB11)
sign16(_BFB11)
if(_BFB11)
copy16(I, _BFB11)
ge16s(_BFB11, _BFB9)
else
copy16(I, _BFB11)
le16s(_BFB11, _BFB9)
endif
while(_BFB11)
alloc_cell16(_BFB12)
alloc_cell16(_BFB13)
copy16(I, _BFB13)
get_array16(A, _BFB13, _BFB12)
free_cell16(_BFB13)
print_cell16s(_BFB12)
free_cell16(_BFB12)
add16s(I, _BFB10)
copy16(_BFB10, _BFB11)
sign16(_BFB11)
if(_BFB11)
copy16(I, _BFB11)
ge16s(_BFB11, _BFB9)
else
copy16(I, _BFB11)
le16s(_BFB11, _BFB9)
endif
endwhile
free_cell16(_BFB8)
free_cell16(_BFB9)
free_cell16(_BFB10)
free_cell16(_BFB11)
END
run_ok("bfpp -o $test.bf $test.bfpp");
capture_ok("bf $test.bf", "8 6 4 2 ");

unlink_testfiles;
done_testing;
