#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# A+B
spew("$test.bas", <<END);
A = 10
B = 5
C = A + B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0  15 
     ^^^ (ptr=0)

END

# A-B
spew("$test.bas", <<END);
A = 10
B = 5
C = A - B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
sub16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0   5 
     ^^^ (ptr=0)

END

# A*B
spew("$test.bas", <<END);
A = 10
B = 5
C = A * B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
mul16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0  50 
     ^^^ (ptr=0)

END

# A/B
spew("$test.bas", <<END);
A = 10
B = 5
C = A / B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
div16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0   2 
     ^^^ (ptr=0)

END

# A\B
spew("$test.bas", <<END);
A = 10
B = 5
C = A \\ B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
div16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0   2 
     ^^^ (ptr=0)

END

# A MOD B
spew("$test.bas", <<END);
A = 10
B = 3
C = A Mod B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 3)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
mod16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   3   0   1 
     ^^^ (ptr=0)

END

# A SHL B
spew("$test.bas", <<END);
A = 10
B = 2
C = A Shl B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 2)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
shl16(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   2   0  40 
     ^^^ (ptr=0)

END

# A SHR B
spew("$test.bas", <<END);
A = 10
B = 2
C = A Shr B
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 2)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
shr16(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   2   0   2 
     ^^^ (ptr=0)

END

# A+B*C
spew("$test.bas", <<END);
A = 2
B = 3
C = 4
D = A + B * C
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
alloc_cell16(D)
set16(A, 2)
set16(B, 3)
set16(C, 4)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
alloc_cell16(_BFB3)
copy16(C, _BFB3)
mul16s(_BFB2, _BFB3)
free_cell16(_BFB3)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, D)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape:  2   0   3   0   4   0  14 
     ^^^ (ptr=0)

END

# A-B/C
spew("$test.bas", <<END);
A = 20
B = 10
C = 3
D = A - B / C
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
alloc_cell16(D)
set16(A, 20)
set16(B, 10)
set16(C, 3)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
alloc_cell16(_BFB3)
copy16(C, _BFB3)
div16s(_BFB2, _BFB3)
free_cell16(_BFB3)
sub16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, D)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 20   0  10   0   3   0  17 
     ^^^ (ptr=0)

END

# (A+B)*C
spew("$test.bas", <<END);
A = 2
B = 3
C = 4
D = (A + B) * C
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
alloc_cell16(D)
set16(A, 2)
set16(B, 3)
set16(C, 4)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
alloc_cell16(_BFB3)
copy16(C, _BFB3)
mul16s(_BFB1, _BFB3)
free_cell16(_BFB3)
move16(_BFB1, D)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape:  2   0   3   0   4   0  20 
     ^^^ (ptr=0)

END

# (A-B)\C
spew("$test.bas", <<END);
A = 10
B = 5
C = 2
D = (A - B) \\ C
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
alloc_cell16(D)
set16(A, 10)
set16(B, 5)
set16(C, 2)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
sub16s(_BFB1, _BFB2)
free_cell16(_BFB2)
alloc_cell16(_BFB3)
copy16(C, _BFB3)
div16s(_BFB1, _BFB3)
free_cell16(_BFB3)
move16(_BFB1, D)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0   2   0   2 
     ^^^ (ptr=0)

END

# A-(-B)
spew("$test.bas", <<END);
A = 10
B = 5
C = A - (-B)
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
neg16(_BFB2)
sub16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0  15 
     ^^^ (ptr=0)

END

# A+(+B)
spew("$test.bas", <<END);
A = 10
B = 5
C = A + (+B)
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", <<END);
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(C)
set16(A, 10)
set16(B, 5)
alloc_cell16(_BFB1)
copy16(A, _BFB1)
alloc_cell16(_BFB2)
copy16(B, _BFB2)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, C)
free_cell16(_BFB1)
END
capture_ok("bfpp $test.bfpp | bf -D", <<END);
Tape: 10   0   5   0  15 
     ^^^ (ptr=0)

END


unlink_testfiles;
done_testing;
