#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# function not defined
spew("$test.bas", <<'END');
PRINT add(2, 4)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: undefined function 'ADD'
END

# subroutine multiply defined
spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: function 'ADD' already defined
END

# wrong number of arguments
spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
PRINT add
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: variable 'ADD' conflicts with subroutine or function name
END

spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
PRINT add()
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: function 'ADD' expects 2 argument(s), got 0
END

spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
PRINT add(1)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: function 'ADD' expects 2 argument(s), got 1
END

spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
PRINT add(1, 2, 3)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: function 'ADD' expects 2 argument(s), got 3
END

# wrong type of arguments
spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add = a + b
ENDFUNCTION
PRINT add("hello", "world")
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 4: argument 1 of 'ADD' expects integer but got string
END

# check recursion
spew("$test.bas", <<'END');
FUNCTION fact(n)
	IF N > 1 THEN
		fact = fact(n-1)
	ELSE
		fact = 1
	ENDIF
ENDFUNCTION
PRINT fact(4)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 3: function 'FACT' cannot call itself (recursion is not supported)
END

# check not returning of values
spew("$test.bas", <<'END');
FUNCTION add(a, b)
	add1 = a + b
ENDFUNCTION
PRINT add(1, 2)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 2: function 'ADD' must assign a return value to 'ADD'
END

# check duplicate names variable and sub
spew("$test.bas", <<'END');
hello = 3
FUNCTION hello()
	hello = 0
ENDFUNCTION
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

spew("$test.bas", <<'END');
DIM hello(3)
FUNCTION hello()
	hello = 0
ENDFUNCTION
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

spew("$test.bas", <<'END');
LET A = hello ^ 2
FUNCTION hello()
	hello = 0
ENDFUNCTION
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<END);
Error at line 1: variable 'HELLO' conflicts with subroutine or function name
END

# FUNCTION call with inlining and use of global vars
spew("$test.bas", <<'END');
FUNCTION add(a, b)
	result = a + b
	add = result
	G = G + result
ENDFUNCTION
PRINT add(1, 2) + add(3, 4); G
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(ADD_1_A)
alloc_cell16(ADD_1_ADD)
alloc_cell16(ADD_1_B)
alloc_cell16(ADD_1_RESULT)
alloc_cell16(ADD_2_A)
alloc_cell16(ADD_2_ADD)
alloc_cell16(ADD_2_B)
alloc_cell16(ADD_2_RESULT)
alloc_cell16(G)
set16(ADD_1_A, 1)
set16(ADD_1_B, 2)
set16(ADD_1_RESULT, 3)
set16(ADD_1_ADD, 3)
alloc_cell16(_BFB1)
copy16(G, _BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 3)
add16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, G)
free_cell16(_BFB1)
set16(ADD_2_A, 3)
set16(ADD_2_B, 4)
set16(ADD_2_RESULT, 7)
set16(ADD_2_ADD, 7)
alloc_cell16(_BFB3)
copy16(G, _BFB3)
alloc_cell16(_BFB4)
set16(_BFB4, 7)
add16s(_BFB3, _BFB4)
free_cell16(_BFB4)
move16(_BFB3, G)
free_cell16(_BFB3)
alloc_cell16(_BFB5)
set16(_BFB5, 10)
print_cell16s(_BFB5)
free_cell16(_BFB5)
print_cell16s(G)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", <<'END');
10 10 
END

# function with string arguments and result
spew("$test.bas", <<'END');
FUNCTION cat$(a$, b$)
	cat$ = a$ & " " & b$
ENDFUNCTION
PRINT cat$("hello", "world")
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(CAT$_1_A$, 6)
alloc_array8(CAT$_1_B$, 6)
alloc_array8(CAT$_1_CAT$, 12)
set_string(CAT$_1_A$, "hello")
set_string(CAT$_1_B$, "world")
set_string(CAT$_1_CAT$, "hello world")
print_string(CAT$_1_CAT$)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", <<'END');
hello world
END

# inlining in two levels
spew("$test.bas", <<'END');
FUNCTION s1(a, b)
	s1 = s2(a + b) * s2(a - b)
ENDFUNCTION
FUNCTION s2(n)
	s2 = n^2
ENDFUNCTION
PRINT s1(2, 4)
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(S1_1_A)
alloc_cell16(S1_1_B)
alloc_cell16(S1_1_S1)
alloc_cell16(S2_1_N)
alloc_cell16(S2_1_S2)
alloc_cell16(S2_2_N)
alloc_cell16(S2_2_S2)
set16(S1_1_A, 2)
set16(S1_1_B, 4)
set16(S2_1_N, 6)
set16(S2_1_S2, 36)
set16(S2_2_N, -2)
set16(S2_2_S2, 4)
set16(S1_1_S1, 144)
alloc_cell16(_BFB1)
set16(_BFB1, 144)
print_cell16s(_BFB1)
free_cell16(_BFB1)
print_newline
END
capture_ok("bfpp $test.bfpp | bf", <<'END');
144 
END

# test inlining when arguments are not constant
spew("$test.bas", <<'END');
FUNCTION square(n)
	square = n^2
ENDFUNCTION
INPUT a
PRINT a; square(a); square(square(a))
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(SQUARE_1_N)
alloc_cell16(SQUARE_1_SQUARE)
alloc_cell16(SQUARE_2_N)
alloc_cell16(SQUARE_2_SQUARE)
alloc_cell16(SQUARE_3_N)
alloc_cell16(SQUARE_3_SQUARE)
scan_cell16s(A)
copy16(A, SQUARE_1_N)
alloc_cell16(_BFB1)
copy16(SQUARE_1_N, _BFB1)
alloc_cell16(_BFB2)
set16(_BFB2, 2)
pow16s(_BFB1, _BFB2)
free_cell16(_BFB2)
move16(_BFB1, SQUARE_1_SQUARE)
free_cell16(_BFB1)
copy16(A, SQUARE_2_N)
alloc_cell16(_BFB3)
copy16(SQUARE_2_N, _BFB3)
alloc_cell16(_BFB4)
set16(_BFB4, 2)
pow16s(_BFB3, _BFB4)
free_cell16(_BFB4)
move16(_BFB3, SQUARE_2_SQUARE)
free_cell16(_BFB3)
copy16(SQUARE_2_SQUARE, SQUARE_3_N)
alloc_cell16(_BFB5)
copy16(SQUARE_3_N, _BFB5)
alloc_cell16(_BFB6)
set16(_BFB6, 2)
pow16s(_BFB5, _BFB6)
free_cell16(_BFB6)
move16(_BFB5, SQUARE_3_SQUARE)
free_cell16(_BFB5)
print_cell16s(A)
print_cell16s(SQUARE_1_SQUARE)
print_cell16s(SQUARE_3_SQUARE)
print_newline
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("echo 3 | bf $test.bf", <<'END');
3 9 81 
END

unlink_testfiles;
done_testing;
