#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# INPUT
spew("$test.bas", <<'END');
INPUT
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 2: Expected variable name after INPUT
END

# INPUT A,
spew("$test.bas", <<'END');
INPUT A,
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 2: Expected variable name after ,
END

# INPUT A$ without DIM
spew("$test.bas", <<'END');
INPUT A$
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 1: string variable 'A$' must be declared by DIM before used
END

SKIP: {
	skip "INPUT A(I) not implemented yet", 1;
# INPUT A(1) without DIM
spew("$test.bas", <<'END');
INPUT A(1)
END
capture_nok("bfbasic $test.bas -o $test.bfpp", <<'END');
Error at line 2: Expected variable name after ,
END
}

# INPUT A
spew("$test.bas", <<'END');
INPUT A
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
scan_cell16s(A)
END
run_ok("bfpp $test.bfpp > $test.bf");
capture_ok("echo 10 | bf -D $test.bf", <<'END');
Tape: 10   0   0   0   0   0   0   0   0  10 
     ^^^ (ptr=0)

END

# INPUT A, B
spew("$test.bas", <<'END');
INPUT A, B
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
scan_cell16s(A)
scan_cell16s(B)
END
run_ok("bfpp $test.bfpp > $test.bf");
capture_ok("echo 10 20 | bf -D $test.bf", <<'END');
Tape: 10   0  20   0   0   0   0   0   0   0   0  10 
     ^^^ (ptr=0)

END

# INPUT A$
spew("$test.bas", <<'END');
DIM A$(10)
INPUT A$
PRINT "Hello " & A$ & "!"
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_array8(A$, 11)
scan_word(A$)
alloc_array8(_BFB1$, 18)
alloc_array8(_BFB2$, 17)
alloc_array8(_BFB3$, 7)
set_string(_BFB3$, "Hello ")
set_string(_BFB2$, _BFB3$)
append_string(_BFB2$, A$)
free_array8(_BFB3$)
alloc_array8(_BFB4$, 2)
set_string(_BFB4$, "!")
set_string(_BFB1$, _BFB2$)
append_string(_BFB1$, _BFB4$)
free_array8(_BFB2$)
free_array8(_BFB4$)
print_string(_BFB1$)
free_array8(_BFB1$)
print_newline
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("echo John | bf $test.bf", <<'END');
Hello John!
END

SKIP: {
	skip "INPUT A(I) not implemented yet", 1;
# INPUT A(i)
spew("$test.bas", <<'END');
DIM A(2)
INPUT A(1), A(2)
PRINT A(1);A(2)
END
run_ok("bfbasic $test.bas -o $test.bfpp");
check_text_file("$test.bfpp", <<'END');
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
scan_cell16s(A)
scan_cell16s(B)
END
run_ok("bfpp $test.bfpp -o $test.bf");
capture_ok("echo 11 42 | bf $test.bf", <<'END');
11 42 
END
}

unlink_testfiles;
done_testing;
