#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# show usage
capture_nok("bfbasic -x", <<END);
usage: bfbasic [-o output_file] input_file
END

capture_nok("bfbasic -o", <<END);
bfpp: missing filename after -o
END

capture_nok("bfbasic input1 input2", <<END);
usage: bfbasic [-o output_file] input_file
END

# minimal bfbasic program
spew("$test.bas", <<END);
LET A = 10
LET B = A + 3
INPUT X
LET Y = X * B
PRINT Y
END

my $compiled = <<END;
// Generated by bfbasic, see https://github.com/pauloscustodio/bf
alloc_cell16(A)
alloc_cell16(B)
alloc_cell16(X)
alloc_cell16(Y)
set16(A, 10)
set16(B, 13)
scan_cell16s(X)
alloc_cell16(_BFB1)
copy16(X, _BFB1)
mul16s(_BFB1, B)
move16(_BFB1, Y)
free_cell16(_BFB1)
print_cell16s(Y)
print_newline
END

# parse from stdin, output to stdout
capture_ok("bfbasic < $test.bas", $compiled);

# parse from stdin, output to file
run_ok("bfbasic -o $test.bfpp < $test.bas");
check_text_file("$test.bfpp", $compiled);

# parse from input file, output to file
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", $compiled);

# parse from input file, output to stdout
capture_ok("bfbasic $test.bas", $compiled);

# convert to bf
run_ok("bfpp -o $test.bf $test.bfpp");

# run the code
capture_ok("echo 27 | bf $test.bf", <<END);
351 
END

# check the same BASIC program with colons
spew("$test.bas", <<END);
LET A = 10 : : LET B = A + 3 :

INPUT X : LET Y = X * B : PRINT Y
:
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", $compiled);

# check the same BASIC program with _
spew("$test.bas", <<END);
LET _
A _
= _
10 _
: _
: _
LET _
B _
= _
A _
+ _
3 _
: _
INPUT _
X _
: _
LET _
Y _
= _
X _
* _
B _
: _
PRINT _
Y _
END
run_ok("bfbasic -o $test.bfpp $test.bas");
check_text_file("$test.bfpp", $compiled);

# test final _ in the file
spew("$test.bas", "LET A = 10 : LET B = A + 3 : INPUT X : LET Y = X * B : PRINT Y _");
capture_nok("bfbasic -o $test.bfpp $test.bas", <<END);
Error at line 1: Line continuation '_' must be followed by a newline
END

unlink_testfiles;
done_testing;
