#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# clear_string - error no arguments
spew("$test.in", "clear_string");
capture_nok("bfpp $test.in", <<END);
$test.in:1:13: error: expected '(' after macro name 'clear_string'
END

# clear_string - error empty arguments
spew("$test.in", "clear_string()");
capture_nok("bfpp $test.in", <<END);
$test.in:1:15: error: macro 'clear_string' expects 1 argument
END

# clear_string - error too many arguments
spew("$test.in", "clear_string(A,B)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:15: error: expected ')' at end of macro call, found ','
END

# clear_string - wrong type of arguments
spew("$test.in", "clear_string(1)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:16: error: address 1 is not an alloc_array result
END

# clear_string - use as reserved word
spew("$test.in", "#define clear_string 1");
capture_nok("bfpp $test.in", <<END);
$test.in:1:9: error: cannot define macro 'clear_string': reserved word
END

# alloc_array8, set string
spew("$test.in", <<'END');
alloc_array8(A$, 5+1)
set_string(A$, "hello")
clear_string(A$)
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  621 instructions, 7 tape cells
]
[-]>[-]>[-]>[-]>[-]>[-]<<<<<[-]+++++>[-]++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++>[-]++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++>[-]+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++>[-]+++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++>[-]+++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++<<<<<[-]>[-]>[-]>[-]>[-]>[-]<<<<<
END
capture_ok("bfpp $test.in | bf -D", <<END);
Tape:  0 
     ^^^ (ptr=0)

END

unlink_testfiles;
done_testing;
