#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# eq8s - error no arguments
spew("$test.in", "eq8s");
capture_nok("bfpp $test.in", <<END);
$test.in:1:5: error: expected '(' after macro name 'eq8s'
END

# eq8s - error empty arguments
spew("$test.in", "eq8s()");
capture_nok("bfpp $test.in", <<END);
$test.in:1:7: error: macro 'eq8s' expects 2 arguments
END

# eq8s - error too many arguments
spew("$test.in", "eq8s(A,B,C)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:9: error: expected ')' at end of macro call, found ','
END

# eq8s(a,b)
spew("$test.in", <<END);
alloc_cell8(A)
alloc_cell8(B)
eq8s(A,B)
>A
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  103 instructions, 4 tape cells
]
[-]>[-]>[-]>[-]<[-]<[->+>+<<]>>[-<<+>>][-]<[-<<->>][-]>[-]<[-]<<[->>+<<]+>>>+<[-
>[-<<<->>>]<][-]>[-]<<<
END

# run eq8s(a,b)
for my $A (0, 1, 2) {
	for my $B (0, 1, 2) {
		spew("$test.in", <<END);
		alloc_cell8(A)
		alloc_cell8(B)
		set8(A, $A)
		set8(B, $B)
		eq8s(A, B)
		>B
END
		my $R = ($A == $B) ? 1 : 0;
		capture_ok("bfpp $test.in | bf -D", <<END);
Tape:  $R   $B 
         ^^^ (ptr=1)

END
	}
}

unlink_testfiles;
done_testing;
