#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# print_string - error no arguments
spew("$test.in", "print_string");
capture_nok("bfpp $test.in", <<END);
$test.in:1:13: error: expected '(' after macro name 'print_string'
END

# print_string - error empty arguments
spew("$test.in", "print_string()");
capture_nok("bfpp $test.in", <<END);
$test.in:1:15: error: macro 'print_string' expects one string
END

# print_string - error too many arguments
spew("$test.in", "print_string(\"A\", \"B\")");
capture_nok("bfpp $test.in", <<END);
$test.in:1:17: error: expected ')' at end of macro call, found ','
END

# print_string - wrong type of argument
spew("$test.in", "print_string(42)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:17: error: macro 'print_string' expects one string
END

# print_string - print the given string
spew("$test.in", <<END);
print_string("Hello") print_newline
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  537 instructions, 1 tape cells
]
[-]++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.[-]+
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++.[-]++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++.[-]++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++.[-]++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++.[-]++++++++++.[-]
END
capture_ok("bfpp $test.in | bf", <<END);
Hello
END

# print with quotes
spew("$test.in", <<'END'); # Note: quoted 'END'
print_string("Hello \"world\"")
print_newline
END
capture_ok("bfpp $test.in | bf", <<END);
Hello "world"
END

# print_string - print escape sequences
spew("$test.in", <<'END'); # Note: quoted 'END'
print_string("\n, \t, \r, \\, \", \', \0, \a, \b, \f, \v")
END
run_ok("bfpp $test.in | bf > $test.stdout"); 
# Perl blurps on \v: Unrecognized escape \v passed through
my $out = slurp("$test.stdout");
$out =~ s/\r\n/\n/g;
my $exp = "\n, \t, \r, \\, \", \', \0, \a, \b, \f, \x0b";
is $out, $exp, "recognized escape sequences";

unlink_testfiles;
done_testing;
