#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# sub8s - error no arguments
spew("$test.in", "sub8s");
capture_nok("bfpp $test.in", <<END);
$test.in:1:6: error: expected '(' after macro name 'sub8s'
END

# sub8s - error empty arguments
spew("$test.in", "sub8s()");
capture_nok("bfpp $test.in", <<END);
$test.in:1:8: error: macro 'sub8s' expects 2 arguments
END

# sub8s - error too many arguments
spew("$test.in", "sub8s(A,B,C)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:10: error: expected ')' at end of macro call, found ','
END

# sub8s(a,b)
spew("$test.in", <<END);
alloc_cell8(A)
alloc_cell8(B)
sub8s(A,B)
>A
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  56 instructions, 4 tape cells
]
[-]>[-]>[-]>[-]<[-]<[->+>+<<]>>[-<<+>>][-]<[-<<->>][-]<<
END

# run sub8s(a,b)
for my $A (-127, -2, -1, 0, 1, 2, 127) {
	for my $B (-127, -2, -1, 0, 1, 2, 127) {
		my $A8bit = $A & 0xFF;
		my $B8bit = $B & 0xFF;
		spew("$test.in", <<END);
		alloc_cell8(A)
		alloc_cell8(B)
		set8(A, $A8bit)
		set8(B, $B8bit)
		sub8s(A, B)
		>B
END
		my $R = sprintf("%3d", ($A - $B) & 0xFF);
		my $Bout = sprintf("%3d", $B8bit);
		capture_ok("bfpp $test.in | bf -D", <<END);
Tape:$R $Bout 
         ^^^ (ptr=1)

END
	}
}

unlink_testfiles;
done_testing;
