#!/usr/bin/env perl

BEGIN { use lib 't'; require 'testlib.pl'; }

use Modern::Perl;

# scan_char8 - error no arguments
spew("$test.in", "scan_char8");
capture_nok("bfpp $test.in", <<END);
$test.in:1:11: error: expected '(' after macro name 'scan_char8'
END

# scan_char8 - error empty arguments
spew("$test.in", "scan_char8()");
capture_nok("bfpp $test.in", <<END);
$test.in:1:13: error: macro 'scan_char8' expects 1 argument
END

# scan_char8 - error too many arguments
spew("$test.in", "scan_char8(A,B)");
capture_nok("bfpp $test.in", <<END);
$test.in:1:13: error: expected ')' at end of macro call, found ','
END

# scan_char8 - read one character
spew("$test.in", <<END);
alloc_cell8(C)
scan_char8(C)
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  205 instructions, 6 tape cells
]
[-]>>[-]>[-]>[-]<[-]<<[->>+>+<<<]>>>[-<<<+>>>][-]>[-]<[-]<[->+<]+>>+<[->[-<<->>]
<][-]>[-]<[-]<<[-]>[-<+>>+<]>[-<+>][-]>[-]<[-]<<[->>+<<]+>>>+<[->[-<<<->>>]<][-]
>[-]<<<[<<[-]>[-<+>]>-]>[<<<,>>>-]<[-]>[-]<<<
END
run_ok("bfpp $test.in > $test.bf");
capture_ok("echo 0 | bf -D $test.bf", <<END);
Tape: 48 
     ^^^ (ptr=0)

END

# unscan_char8 - unread one character and read it again
spew("$test.in", <<END);
alloc_cell8(C1)
alloc_cell8(C2)
alloc_cell8(C3)
scan_char8(C1)		// '0' = 48
unscan_char8(C1)
scan_char8(C2)		// '0' = 48
scan_char8(C3)		// '1' = 49
END
capture_ok("bfpp $test.in", <<END);
[ Generated by bfpp, see https://github.com/pauloscustodio/bf
  668 instructions, 8 tape cells
]
[-]>[-]>[-]>>[-]>[-]>[-]<[-]<<[->>+>+<<<]>>>[-<<<+>>>][-]>[-]<[-]<[->+<]+>>+<[->
[-<<->>]<][-]>[-]<[-]<<[-]>[-<+>>+<]>[-<+>][-]>[-]<[-]<<[->>+<<]+>>>+<[->[-<<<->
>>]<][-]>[-]<<<[<<<<[-]>>>[-<<<+>>>]>-]>[<<<<<,>>>>>-]<[-]>[-]<[-]<[-]<<<[->>>+>
+<<<<]>>>>[-<<<<+>>>>][-]>[-]>[-]<[-]<<[->>+>+<<<]>>>[-<<<+>>>][-]>[-]<[-]<[->+<
]+>>+<[->[-<<->>]<][-]>[-]<[-]<<[-]>[-<+>>+<]>[-<+>][-]>[-]<[-]<<[->>+<<]+>>>+<[
->[-<<<->>>]<][-]>[-]<<<[<<<[-]>>[-<<+>>]>-]>[<<<<,>>>>-]<[-]>[-]<[-]>[-]>[-]<[-
]<<[->>+>+<<<]>>>[-<<<+>>>][-]>[-]<[-]<[->+<]+>>+<[->[-<<->>]<][-]>[-]<[-]<<[-]>
[-<+>>+<]>[-<+>][-]>[-]<[-]<<[->>+<<]+>>>+<[->[-<<<->>>]<][-]>[-]<<<[<<[-]>[-<+>
]>-]>[<<<,>>>-]<[-]>[-]<<<<<
END
run_ok("bfpp $test.in > $test.bf");
capture_ok("echo 01 | bf -D $test.bf", <<END);
Tape: 48  48  49 
     ^^^ (ptr=0)

END

unlink_testfiles;
done_testing;
