//-----------------------------------------------------------------------------
// Brainfuck Preprocessor
// Copyright (c) Paulo Custodio 2026
// License: The Artistic License 2.0, http ://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "errors.h"
#include "output.h"
#include <algorithm>
#include <cassert>

BFOutput::BFOutput() {
    reset();
}

void BFOutput::put(const Token& tok) {
    if (tok.type != TokenType::BFInstr) {
        g_error_reporter.report_error(
            tok.loc,
            "non-BF instruction token in output: '" + tok.text + "'"
        );
        return;
    }

    if (tok.text == ">") {
        tape_ptr_++;
        max_tape_ptr_ = std::max(max_tape_ptr_, tape_ptr_);
    }
    else if (tok.text == "<") {
        if (tape_ptr_ == 0) {
            g_error_reporter.report_error(
                tok.loc,
                "tape pointer moved to negative position"
            );
            return;
        }
        tape_ptr_--;
    }
    else if (tok.text == "[") {
        loop_stack_.push_back(tok.loc);
    }
    else if (tok.text == "]") {
        if (loop_stack_.empty()) {
            g_error_reporter.report_error(
                tok.loc,
                "unmatched ']' instruction"
            );
            return;
        }
        loop_stack_.pop_back();
    }

    output_.push_back(tok);
}

std::string BFOutput::to_string() const {
    std::string result =
        "[ Generated by bfpp, see https://github.com/pauloscustodio/bf\n"
        "  " + std::to_string(output_.size()) + " instructions, " +
        std::to_string(max_tape_ptr_ + 1) + " tape cells\n"
        "]\n";
    bool at_line_start = true;
    int line_len = 0;

    for (const Token& t : output_) {
        int needed_len = static_cast<int>(t.text.size());
        if (line_len + needed_len > 80) {
            result += '\n';
            at_line_start = true;
            line_len = 0;
        }
        result += t.text;
        line_len += needed_len;
        at_line_start = false;
    }

    if (!at_line_start) {
        result += '\n';
    }

    return result;
}

void BFOutput::check_structures() const {
    for (auto& it : loop_stack_) {
        g_error_reporter.report_error(
            it,
            "unmatched '[' instruction"
        );
    }
}

int BFOutput::tape_ptr() const {
    return tape_ptr_;
}

int BFOutput::alloc_cells(int count) {
    if (count <= 0) {
        return heap_size_; // no-op, but defined behavior
    }

    // First-fit search in free list
    for (std::size_t i = 0; i < free_list_.size(); ++i) {
        int start = free_list_[i].first;
        int len   = free_list_[i].second;
        if (len >= count) {
            // allocate from this block
            int alloc_start = start;
            int remaining = len - count;
            if (remaining == 0) {
                free_list_.erase(free_list_.begin() + static_cast<long>(i));
            }
            else {
                free_list_[i].first = start + count;
                free_list_[i].second = remaining;
            }
            alloc_map_[alloc_start] = count;
            return alloc_start;
        }
    }

    // No free block: extend high watermark
    int alloc_start = heap_size_;
    heap_size_ += count;
    alloc_map_[alloc_start] = count;
    return alloc_start;
}

void BFOutput::add_free_block(int start, int len) {
    if (len <= 0) {
        return;
    }
    // insert and merge
    free_list_.push_back({start, len});
    std::sort(free_list_.begin(), free_list_.end(),
    [](auto & a, auto & b) {
        return a.first < b.first;
    });

    std::vector<std::pair<int, int>> merged;
    for (auto& blk : free_list_) {
        if (merged.empty()) {
            merged.push_back(blk);
            continue;
        }
        auto& back = merged.back();
        int back_start = back.first;
        int back_end = back.first + back.second;
        int blk_start = blk.first;
        int blk_end = blk.first + blk.second;

        if (blk_start <= back_end) { // overlap or adjacent
            int new_end = std::max(back_end, blk_end);
            back.second = new_end - back_start;
        }
        else {
            merged.push_back(blk);
        }
    }
    free_list_.swap(merged);

    // Note: we cannot shrink heap size
    // because bfpp needs to know the maximum heap size used
    // to know where to place the stack
#if 0
    // Optionally shrink heap_size_ if the topmost range reaches the end
    if (!free_list_.empty()) {
        auto& last = free_list_.back();
        int last_end = last.first + last.second;
        if (last_end == heap_size_) {
            // pull heap_size_ down
            heap_size_ = last.first;
            free_list_.pop_back();
        }
    }
#endif
}

void BFOutput::optimize_bfcode() {
    optimize_tape_movements();
    remove_duplicate_clears();
}

void BFOutput::optimize_tape_movements() {
    std::vector<Token> optimized;
    optimized.reserve(output_.size());
    int net_move = 0;
    for (const Token& t : output_) {
        if (t.type == TokenType::BFInstr) {
            if (t.text == ">") {
                net_move++;
            }
            else if (t.text == "<") {
                net_move--;
            }
            else {
                // flush any pending moves
                if (net_move > 0) {
                    for (int i = 0; i < net_move; ++i) {
                        optimized.push_back(Token::make_bf('>', t.loc));
                    }
                }
                else if (net_move < 0) {
                    for (int i = 0; i < -net_move; ++i) {
                        optimized.push_back(Token::make_bf('<', t.loc));
                    }
                }
                net_move = 0;
                optimized.push_back(t);
            }
        }
        else {
            optimized.push_back(t);
        }
    }
    // flush any remaining moves at the end
    if (net_move > 0) {
        for (int i = 0; i < net_move; ++i) {
            optimized.push_back(Token::make_bf('>', SourceLocation()));
        }
    }
    else if (net_move < 0) {
        for (int i = 0; i < -net_move; ++i) {
            optimized.push_back(Token::make_bf('<', SourceLocation()));
        }
    }
    output_.swap(optimized);
}

void BFOutput::remove_duplicate_clears() {
    std::vector<Token> optimized;
    optimized.reserve(output_.size());

    std::size_t i = 0;
    while (i < output_.size()) {
        // Detect a clear pattern "[-]"
        if (i + 2 < output_.size() &&
                output_[i].type == TokenType::BFInstr && output_[i].text == "[" &&
                output_[i + 1].type == TokenType::BFInstr && output_[i + 1].text == "-" &&
                output_[i + 2].type == TokenType::BFInstr && output_[i + 2].text == "]") {

            SourceLocation loc_open = output_[i].loc;
            SourceLocation loc_minus = output_[i + 1].loc;
            SourceLocation loc_close = output_[i + 2].loc;

            i += 3;

            // Consume any subsequent contiguous "[-]" patterns
            while (i + 2 < output_.size() &&
                    output_[i].type == TokenType::BFInstr && output_[i].text == "[" &&
                    output_[i + 1].type == TokenType::BFInstr && output_[i + 1].text == "-" &&
                    output_[i + 2].type == TokenType::BFInstr && output_[i + 2].text == "]") {
                loc_close = output_[i + 2].loc; // keep last closing loc
                i += 3;
            }

            optimized.push_back(Token::make_bf('[', loc_open));
            optimized.push_back(Token::make_bf('-', loc_minus));
            optimized.push_back(Token::make_bf(']', loc_close));
            continue;
        }

        optimized.push_back(output_[i]);
        ++i;
    }

    output_.swap(optimized);
}

void BFOutput::free_cells(int addr) {
    auto it = alloc_map_.find(addr);
    if (it == alloc_map_.end()) {
        g_error_reporter.report_error(
            SourceLocation(),
            "attempt to free unknown allocation at address " + std::to_string(addr)
        );
        return;
    }

    int len = it->second;
    alloc_map_.erase(it);
    add_free_block(addr, len);
}

int BFOutput::alloc_array8(const Token& tok, int cells8) {
    return alloc_arrayN(tok, cells8, 8);
}

void BFOutput::free_array8(const Token& tok, int base_addr) {
    free_arrayN(tok, base_addr);
}

int BFOutput::alloc_array16(const Token& tok, int cells16) {
    return alloc_arrayN(tok, cells16, 16);
}

void BFOutput::free_array16(const Token& tok, int base_addr) {
    free_arrayN(tok, base_addr);
}

int BFOutput::alloc_arrayN(const Token& tok, int num_elems, int width) {
    assert(width == 8 || width == 16);
    int elem_size = width / 8;

    Array array;
    array.loc = tok.loc;
    array.num_elems = num_elems;
    array.elem_size = elem_size;
    array.base_addr = alloc_cells(num_elems * elem_size);
    arrays_[array.base_addr] = array;
    return array.base_addr;
}

void BFOutput::free_arrayN(const Token& tok, int base_addr) {
    Array* array = get_array(base_addr);
    if (array == nullptr) {
        g_error_reporter.report_error(
            tok.loc,
            "cannot free array at address " + std::to_string(base_addr)
        );
        return;
    }

    free_cells(array->base_addr);
}

Array* BFOutput::get_array(int base_addr) {
    auto it = arrays_.find(base_addr);
    if (it == arrays_.end()) {
        return nullptr;
    }
    else {
        return &it->second;
    }
}

void BFOutput::reset() {
    output_.clear();
    arrays_.clear();
    loop_stack_.clear();
    free_list_.clear();
    alloc_map_.clear();
    tape_ptr_ = 0;
    max_tape_ptr_ = 0;
    heap_size_ = 0;
    stack_base_ = stack_ptr_ = min_stack_ptr_ = kInitialStackBase;
    input_buffer_ = -1;
}

void BFOutput::set_stack_base(int base) {
    stack_base_ = stack_ptr_ = min_stack_ptr_ = base;
}

int BFOutput::heap_size() const {
    return heap_size_;
}

int BFOutput::max_stack_depth() const {
    return stack_base_ - min_stack_ptr_;
}

int BFOutput::input_buffer() {
    // if input buffer not allocated, allocate it now
    if (input_buffer_ < 0) {
        input_buffer_ = alloc_cells(1);
    }

    return input_buffer_;
}
